
  # consul
  consul:
    # command: -server -bootstrap
    image: consul:latest
    ports:
      - 8300:8300
      - 8400:8400  # rpc/rest
      - 8500:8500  # ui
      - 8600:8600/udp   # dns
      # - 127.0.0.1:53:53/udp  # dns

  # Nginx Load Balancer
  lb:
    image: 1science/nginx:1.9.6-consul
    ports:
      - 80:80
    # links:
    #   - consul:consul
    volumes:
      - ./etc/consul-template:/etc/consul-template
    # Change this section to point on your Consul
    environment:
      CONSUL_URL: localhost:8500
    net: "host"

  # Registrator to register on local Consul
  registrator:
    image: gliderlabs/registrator:latest
    # links:
    #   - consul:consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    # Change this section to point on your Consul
    command: consul://localhost:8500
    net: "host"

  # Applications

  fake-java:
    build: ./java
    ports:
      - 8080
    volumes:
      - ./fakers:/fakers
    environment:
      SERVICE_NAME: java
    command: ./entrypoint.sh
